# Generated by Django 5.1.2 on 2024-10-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication',
            new_name='publication_date',
        ),
    ]
