# Generated by Django 4.2.11 on 2024-10-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(default='2000-02-02'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.DateField(default='2000-02-02'),
        ),
    ]
